### ISSUE TITLE
TS: export 'default' (imported as 'Flag') was not found in 'react-flagpack' (module has no exports)

### ISSUE THREAD

**Issue by Arakash** [Yummygum/react-flagpack#45]
Hi,

I just updated flagpack and I get this error when trying to import the Flag Component:
```
import Flag from 'react-flagpack'
```
I tried fixing it for a few hours, but I'm at my witts end. 

I use react + typescript with webpack 5.

error looks like this:
```
WARNING in ./src/app/Widgets/DualCountryFlag.tsx 14:36-40
export 'default' (imported as 'Flag') was not found in 'react-flagpack' (module has no exports)
 @ ./src/app/CertificateViewer/rowInput.tsx 15:0-57 148:36-51
```

Any help would be appreciated :)

**Comment by pressstartearly** [comment]
Any luck with this? I'm getting a similar issue. 

```
react-flag-rollup.cjs.js:7 Uncaught ReferenceError: module is not defined
    at node_modules/react-flagpack/dist/react-flag-rollup.cjs.js (react-flag-rollup.cjs.js:7)
    at __init (chunk-ZV2PBCME.js?v=af858b7b:45)
    at dep:react-flagpack:1
```

**Comment by CreativePhilip** [comment]
Issue happens for me using CRA with react `18.1.0`

**Comment by jimburbfs** [comment]
Same issue happening when I tried to use this.

**Comment by yoavsbg** [comment]
same issue here.

**Comment by Olu93** [comment]
same here

**Comment by april21dev** [comment]
same here

**Comment by philhagger** [comment]
Still happening

**Comment by Swarzox** [comment]
same problem nice support

**Comment by zoeyfrisart** [comment]
I completely understand the frustration, unfortunately as Yummygum is a digital agency, priority is given to client projects. This results in us being able to spend less time than we would like on projects such as Flagpack.

There are changes that we aim to implement in Flagpack, however since these changes are rather large they take more time and since we do not get much time to work on Flagpack this is likely to remain an issue for a while.

While I would love to be able to provide somewhat of a timeframe, sadly I am unable to do so at this moment.
Since the code is open source anyone is more than welcome to try and resolve this issue, just give me a ping if you make a pull request and I'll make sure the pull request gets through and released.

**Comment by niteshnagar1432** [comment]
i am also getting same issue?

**Comment by zoeyfrisart** [comment]
Hi all, this should now be resolved, in case you're still facing issues after upgrading to Version 2.0.2, please open up a new issue 🙏
